apiVersion: v1
kind: ConfigMap
metadata:
  name: wedding-frontend-config
  namespace: wedding-frontend
data:
  PUBLIC_API_BASE_URL: 'https://api.example.com'
  API_INTERNAL_BASE_URL: 'https://api.example.com'
  PUBLIC_APP_BASE_PATH: '/'
  AUTH_COOKIE_SECURE: 'true'
  PUBLIC_AUTH_COOKIE_SECURE: 'true'
