apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wedding-frontend
  namespace: wedding-frontend
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: front.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wedding-frontend
                port:
                  number: 80
