apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wedding-frontend
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment-frontend.yaml
  - service-frontend.yaml
  - ingress.yaml
